/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.dsassign1;

import javax.swing.*;

/**
 *
 * @author muham
 */
public class GUI extends javax.swing.JFrame {



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Confirm_Button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;

    private javax.swing.JTextField textfield = new JTextField(16);

    private boolean request = false;


    public boolean isRequest(){
        return request;
    }

    private void setRequest(boolean r){
        this.request = r;
    }

    public JTextField getTextfield() {
        return textfield;
    }

    public void setTextfield(JTextField textfield) {
        this.textfield = textfield;
    }



    public Person getStudentName() {
        return studentName;
    }

    public void setStudentName(Person studentName) {
        this.studentName = studentName;
    }

    private Person studentName = new Person("0", getTextfield().getText());


    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form GUI
     */
    public GUI() {
        System.out.println("HGeöl");
        initComponents();
        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Confirm_Button = new javax.swing.JButton();
        //Label
        JLabel JLNamePrompt = new JLabel("Name: ");
        JLNamePrompt.setBounds(10,20,80,25);
        jPanel1.add(JLNamePrompt);

        //TextField

        textfield.setBounds(100,20,165,25);
        jPanel1.add(textfield);



        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Confirm_Button.setText("Confim");
        Confirm_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Confirm_ButtonActionPerformed(evt);
                setRequest(true);
                System.out.println("Your name is: " + getTextfield().getText());
            }
        });


        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(Confirm_Button)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addComponent(Confirm_Button)
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );




        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Confirm_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Confirm_ButtonActionPerformed
        // TODO add your handling code here:
        setRequest(true);
        System.out.println("Hello World!");
    }//GEN-LAST:event_Confirm_ButtonActionPerformed



}
